### ISSUE TITLE
I am getting this panic error.

### ISSUE THREAD

**Issue by Duckduckgot** [tulir/whatsmeow#110]
`[Client WARN] Got untrusted identity error while trying to process prekey bundle for xxxxxxx9344@s.whatsapp.net, clearing stored identity and retrying[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7ff7fd5241fa]

goroutine 68158 [running]:
go.mau.fi/libsignal/state/record.(*State).SenderChainKey(...)
        C:/Go/go/pkg/mod/go.mau.fi/libsignal@v0.0.0-20220425070825-c40c839ee6a0/state/record/SessionState.go:297
go.mau.fi/libsignal/session.(*Cipher).Encrypt(0xc0017b9a70, {0xc00084e500, 0x1cda, 0x2500})
        C:/Go/go/pkg/mod/go.mau.fi/libsignal@v0.0.0-20220425070825-c40c839ee6a0/session/SessionCipher.go:71 +0x7a
go.mau.fi/whatsmeow.(*Client).encryptMessageForDevice(0xc000200000, {0xc0009ea000, 0x1cd8, 0x1cd8}, {{0xc0004558a0, 0xb}, 0x0, 0x0, {0x7ff7fd82324c, 0xe}, ...}, ...)
        C:/wago/wago/whatsmeow/send.go:366 +0x67d
go.mau.fi/whatsmeow.(*Client).handleRetryReceipt(0xc000200000, 0xc0011e0c40, 0xc00096d650)
        C:/wago/wago/whatsmeow/retry.go:152 +0xec5
go.mau.fi/whatsmeow.(*Client).handleReceipt.func1()
        C:/wago/wago/whatsmeow/receipt.go:26 +0x33
created by go.mau.fi/whatsmeow.(*Client).handleReceipt
        C:/wago/wago/whatsmeow/receipt.go:25 +0xcf`

**Comment by moxovil** [comment]
I have the same problem

**Comment by gabrielphilipes** [comment]
Good Morning! I have the same problem, it started a few days ago.

**Comment by elie-atia** [comment]
Same problem also, thanks for the help people..

**Comment by HoshenKadosh** [comment]
have the same error.. any way to prevent it from panic and crashing all?

**Comment by GustavoGSA** [comment]
I have the same problem.
