### ISSUE TITLE
go.mau.fi/libsignal/state/record.(*State).SenderChainKey(...)

### ISSUE THREAD

**Issue by Romerito007** [tulir/whatsmeow#114]
````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc9c7fa]

goroutine 37664 [running]:
go.mau.fi/libsignal/state/record.(*State).SenderChainKey(...)
	/home/romerito007/go/src/go.mau.fi/libsignal/state/record/SessionState.go:297
go.mau.fi/libsignal/session.(*Cipher).Encrypt(0xc0013639c8, {0xc0010fae00, 0x18a, 0x380})
	/home/romerito007/go/src/go.mau.fi/libsignal/session/SessionCipher.go:71 +0x7a
go.mau.fi/whatsmeow.(*Client).encryptMessageForDevice(0xc000b2e000, {0xc0012ce000, 0x189, 0x189}, {{0xc0010808f0, 0xc}, 0x0, 0x0, {0x12705aa, 0xe}, ...}, ...)
	/home/romerito007/go/src/go.mau.fi/whatsmeow/send.go:375 +0x67d
go.mau.fi/whatsmeow.(*Client).handleRetryReceipt(0xc000b2e000, 0xc000a78460, 0xc00090cff0)
	/home/romerito007/go/src/go.mau.fi/whatsmeow/retry.go:159 +0x1189
go.mau.fi/whatsmeow.(*Client).handleReceipt.func1()
	/home/romerito007/go/src/go.mau.fi/whatsmeow/receipt.go:26 +0x33
created by go.mau.fi/whatsmeow.(*Client).handleReceipt
	/home/romerito007/go/src/go.mau.fi/whatsmeow/receipt.go:25 +0xcf
````

**Comment by Duckduckgot** [comment]
I have the same error [110](https://github.com/tulir/whatsmeow/issues/110#issue-1222131101)

**Comment by GustavoGSA** [comment]
The same error here, any solution?
