### ISSUE TITLE
panic: interface conversion: interface {} is []binary.Node, not []uint8

### ISSUE THREAD

**Issue by Romerito007** [tulir/whatsmeow#16]
`panic: interface conversion: interface {} is []binary.Node, not []uint8

goroutine 175 [running]:
go.mau.fi/whatsmeow.(*Client).parseGroupChange(0xc000801380, 0xc000caa390)
	/home/romerito007/go/src/go.mau.fi/whatsmeow/group.go:446 +0x143d
go.mau.fi/whatsmeow.(*Client).parseGroupNotification(0x1262348, 0xc000674330)
	/home/romerito007/go/src/go.mau.fi/whatsmeow/group.go:485 +0x99
go.mau.fi/whatsmeow.(*Client).handleNotification(0xc0000d03c0, 0xc000caa390)
	/home/romerito007/go/src/go.mau.fi/whatsmeow/notification.go:86 +0x1db
go.mau.fi/whatsmeow.(*Client).handlerQueueLoop(0xc0000d03c0, {0x14bea58, 0xc000851880})
	/home/romerito007/go/src/go.mau.fi/whatsmeow/client.go:382 +0x6b
created by go.mau.fi/whatsmeow.(*Client).Connect
	/home/romerito007/go/src/go.mau.fi/whatsmeow/client.go:162 +0x425
time="2021-11-05T14:15:50-03:00" level=info msg="Create connection database" label="Initializing connection creation:" service=smartt-srv
time="2021-11-05T14:15:50-03:00" level=info msg="Server worker started at PID: 1 listening on 0.0.0.0:3000" label=http-server service=smartt-srv
time="2021-11-05T14:15:50-03:00" level=info msg="Database connection successful" label="INFO DATABASE:" service=smartt-srv`

**Comment by Romerito007** [comment]
> Can you try again with that commit and see what the error is? (alternatively, if you had debug logs enabled, just check a few lines before the panic to find the XML content)

I will enable logs.

**Comment by Romerito007** [comment]
I will close this issue, if it occurs I will put the logs.
