### ISSUE TITLE
The resulting panic caused the program to crash

### ISSUE THREAD

**Issue by sodaling** [tulir/whatsmeow#189]
```shell
{"level":"error","time":"2022-06-28T09:52:59.883-0500","caller":"whatsmeow@v0.0.0-20220614154415-5718022af87c/message.go:336","msg":"Failed to do initial fetch of app state regular: failed to fetch app state regular patches: websocket not connected","user":"500002-31","stacktrace":"go.mau.fi/whatsmeow.(*Client).handleAppStateSyncKeyShare\n\t/home/rdev/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/message.go:336"}
{"level":"error","time":"2022-06-28T09:52:59.883-0500","caller":"whatsmeow@v0.0.0-20220614154415-5718022af87c/message.go:336","msg":"Failed to do initial fetch of app state regular_low: failed to fetch app state regular_low patches: websocket not connected","user":"500002-31","stacktrace":"go.mau.fi/whatsmeow.(*Client).handleAppStateSyncKeyShare\n\t/home/rdev/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/message.go:336"}
{"level":"info","time":"2022-06-28T09:52:59.884-0500","caller":"whatsmeow@v0.0.0-20220614154415-5718022af87c/appstate.go:269","msg":"Sending key request for app state keys [00000000e485 00470000e474 003f0000e46d 00000000e46a 00000000e467 00000000e472 00010000e498 00000000e495 00000000e49d 00000000e47e 00000000e455 00000000e492 00000000e483 00000000e494 00000000e462 00010000e4a4 00000000e47a 003e0000e46b 00000000e47b 00000000e48d 00000000e479 00000000e480 00470000e477 00010000e48a 001d0000e4a2 00000000e473 00000000e458 00000000e49c 00000000e489 00000000e481 00000000e45b 00000000e478 00000000e460 00010000e490 00000000e484 00000000e456 00000000e46f 00000000e487 00360000e464 00000000e470 00000000e486 00000000e4a3 00000000e499 00000000e49e 00000000e466 00000000e461 00000000e497 00000000e46e 00000000e465 00000000e475 00000000e468 00000000e457 00000000e47d 00000000e48e 00000000e463 00000000e459 00000000e476 00000000e49f 00000000e47f 00000000e471 00000000e4a0 00000000e45a 00000000e46c 00000000e47c 00010000e48f 00000000e49a 00000000e488 00000000e482 00000000e469]","user":"500002-31"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa84ec3]
goroutine 400692 [running]:
go.mau.fi/whatsmeow.(*Client).requestAppStateKeys(0xc002f56800, {0xc0019c7500, 0x45, 0xc})
        /home/rdev/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/appstate.go:270 +0x223
go.mau.fi/whatsmeow.(*Client).requestMissingAppStateKeys(0xc002f56800, 0xc003565800)
        /home/rdev/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/appstate.go:251 +0x11c
created by go.mau.fi/whatsmeow.(*Client).FetchAppState
        /home/rdev/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220614154415-5718022af87c/appstate.go:59 +0x935
```

My program reported a panic.
First of all I can't figure out what's wrong with this error.
Then because this groutine is derived from whatsmeow. So I couldn't revocery effectively after panic, which caused the whole program to crash.
Maybe whatsmeow should pay attention to revocery when spawning groutines before finding the cause of this problem?

**Comment by tulir** [comment]
Moving to #295
