### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#229]
I got the below error:
```bash
2022/08/13 00:13:31 http: panic serving [::1]:60132: runtime error: invalid memory address or nil pointer dereference
goroutine 99 [running]:
net/http.(*conn).serve.func1()
        D:/Development/go/src/net/http/server.go:1825 +0xbf panic({0x8d5800, 0x830ea0})
        D:/Development/go/src/runtime/panic.go:844 +0x258 wa/server.reply({0xa9a230, 0xc0000f2380}, 0xc000618c00)
        D:/wa/server/reply.go:56 +0x6dc net/http.HandlerFunc.ServeHTTP(0x2030000?, {0xa9a230?, 0xc0000f2380?}, 0xc0003b1a80?)
        D:/Development/go/src/net/http/server.go:2084 +0x2f net/http.(*ServeMux).ServeHTTP(0x0?, {0xa9a230, 0xc0000f2380}, 0xc000618c00)
        D:/Development/go/src/net/http/server.go:2462 +0x149 net/http.serverHandler.ServeHTTP({0xa99160?}, {0xa9a230, 0xc0000f2380}, 0xc000618c00)
        D:/Development/go/src/net/http/server.go:2916 +0x43b net/http.(*conn).serve(0xc00026a5a0, {0xa9a638, 0xc000288630})
        D:/Development/go/src/net/http/server.go:1966 +0x5d7 created by net/http.(*Server).Serve
        D:/Development/go/src/net/http/server.go:3071 +0x4db
```

Line 56 from the error above is:
```go
Log.Infof("Message sent (server timestamp: %s)", send)
``` 
At the below code, noting that the message had been sent correctly and recieved by the correct jid, the code is:
```go
package server

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"wa/api"
	"wa/globals"
	"wa/utils"

	waProto "go.mau.fi/whatsmeow/binary/proto"
	waLog "go.mau.fi/whatsmeow/util/log"
	"google.golang.org/protobuf/proto"
)

type Reply struct {
	Sender  string `json:"sender"`
	Message string `json:"message"`
}

var Log waLog.Logger

func reply(w http.ResponseWriter, r *http.Request) {

	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
	w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")

	// Declare a new struct to hold the json data.
	var rply Reply

	// Try to decode the request body into the struct. If there is an error,
	// respond to the client with the error message and a 400 status code.
	err := json.NewDecoder(r.Body).Decode(&rply)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	fmt.Println("reply:", rply)

	msg := &waProto.Message{
		Conversation: proto.String(rply.Message),
	}

	jid, ok := utils.ParseJID(rply.Sender)
	if !ok {
		return
	}
	send, err := api.Client.SendMessage(context.Background(), jid, "", msg) // jid = recipient

	if err != nil {
		Log.Errorf("Error sending message: %v", err)
	} else {
		Log.Infof("Message sent (server timestamp: %s)", send)
	}

	w.WriteHeader(http.StatusCreated)
	w.Header().Set("Content-Type", "application/json")
	resp := make(map[string]string)
	resp["message"] = "Message sent"
	jsonResp, err := json.Marshal(resp)
	if err != nil {
		log.Fatalf("Error happened in JSON marshal. Err: %s", err)
	}
	w.Write(jsonResp)
}
```

And the message is sent from JavaScript as:
```JavaScript
    fetch('http://localhost:1234/reply', {
      method: 'POSTS',
      headers: {
        'Content-Type': 'application/json',
      },
       body: JSON.stringify({
         // your expected POST request payload goes here
         sender: sender,
         message: replyText
          })
    }) 
    .then(res => res.json())
    .then(data => {
       // enter you logic when the fetch is successful
       reply.value = ""
       e.parentNode.parentNode.appendChild(r)
        alert(data.message)
      })
      .catch(error => {
      // enter your logic for when there is an error (ex. error toast)
      reply.value = ""
      e.parentNode.parentNode.appendChild(r)
       alert(data.message)
    //  alert(error)
     }) 
```

Note: The error started appearing after updating to the new version, and starting using `context.Background()` at `Client.SendMessage` not sure if this is the reason or something else.

**Comment by tulir** [comment]
Your `var Log waLog.Logger` looks nil

**Comment by rvp98** [comment]
Hello @hajsf, how to solve this kind of issue?

**Comment by GustavoGSA** [comment]
I have the same error.
