### ISSUE TITLE
Panic when trying to decrypt incoming message

### ISSUE THREAD

**Issue by serenity-77** [tulir/whatsmeow#233]
This maybe happen after signal decryption somehow returns empty plaintext.

![Screenshot from 2022-08-22 11-57-28](https://user-images.githubusercontent.com/42235678/185842771-a7012a44-ce79-480b-a357-ee00d169a2ea.png)

 
```
panic: runtime error: index out of range [-1]

goroutine 503 [running]:
go.mau.fi/whatsmeow.isValidPadding({0xc0000ef420?, 0xcc3e38?, 0x134d480?})
	/disk1/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220804175245-31c5af44cb82/message.go:243 +0x1d6
go.mau.fi/whatsmeow.unpadMessage({0xc0000ef420, 0x0, 0x70})
	/disk1/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220804175245-31c5af44cb82/message.go:249 +0x2c
go.mau.fi/whatsmeow.(*Client).decryptDM(0xc0008cf800, 0xbbe500?, {{0xc004076690, 0xd}, 0x0, 0x0, {0xbc7068, 0xe}, 0x0}, 0x0)
	/disk1/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220804175245-31c5af44cb82/message.go:220 +0x731
go.mau.fi/whatsmeow.(*Client).decryptMessages(0xc0008cf800, 0xc000b74fc0, 0xc0020363c0)
	/disk1/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220804175245-31c5af44cb82/message.go:147 +0x6c7
go.mau.fi/whatsmeow.(*Client).handleEncryptedMessage(0xc0008cf800, 0x0?)
	/disk1/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220804175245-31c5af44cb82/message.go:49 +0x33f
go.mau.fi/whatsmeow.(*Client).handlerQueueLoop(0xc0008cf800, {0xcc59d8, 0xc0003918c0})
	/disk1/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220804175245-31c5af44cb82/client.go:532 +0x6b
created by go.mau.fi/whatsmeow.(*Client).Connect
	/disk1/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220804175245-31c5af44cb82/client.go:290 +0x45b
```

**Comment by Paguiar735** [comment]
Can you share the content of the incoming message that causes this behavior?
