### ISSUE TITLE
Panic when try to reconnect to the account

### ISSUE THREAD

**Issue by rvp98** [tulir/whatsmeow#234]
i got this error when try to reconnect with my account before sending a message

<html>
<body>

APP/PROC/WEB | 0 | 01:24:43.921 [Client/Socket DEBUG] Dialing wss://web.whatsapp.com/ws/chat[0m | Aug 23, 2022, 08:24:43 AM
-- | -- | -- | --
APP/PROC/WEB | 0 | 2022/08/23 01:24:44 http: panic serving 10.247.223.14:58128: runtime error: invalid memory address or nil pointer dereference | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | goroutine 673 [running]: | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | net/http.(*conn).serve.func1() | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | /tmp/contents4091003199/deps/0/go1.18.5/src/net/http/server.go:1825 +0xbf | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | panic({0x55a9b56400e0, 0x55a9b5a3cef0}) | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | /tmp/contents4091003199/deps/0/go1.18.5/src/runtime/panic.go:844 +0x258 | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | go.mau.fi/whatsmeow.(*Client).doHandshake(0xc0002d6000, 0xc00031f340, {0xc00014cd80?, 0xc00014cd60?}) | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | /tmp/app/vendor/go.mau.fi/whatsmeow/handshake.go:98 +0xba0 | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | go.mau.fi/whatsmeow.(*Client).Connect(0xc0002d6000) | Aug 23, 2022, 08:24:44 AM
APP/PROC/WEB | 0 | /tmp/app/vendor/go.mau.fi/whatsmeow/client.go:285 +0x27e

</body>
</html>

**Comment by Paguiar735** [comment]
What do you mean by "before sending a message"? Does that mean that the errors go away once you send a message? If so, are you referring to sending a message from your mobile device or from whatsmeow?
