### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by chagai95** [tulir/whatsmeow#457]
I turned on debug logs but I'm still not seeing more than this:
```
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9f6f3d]
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: goroutine 30938 [running]:
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: go.mau.fi/whatsmeow.(*Client).getOwnID(...)
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]:         /builds/mautrix/whatsapp/.cache/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230816173759-58beaf3b5bd0/client.go:274
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: go.mau.fi/whatsmeow.(*Client).GenerateMessageID(0x0)
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]:         /builds/mautrix/whatsapp/.cache/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20230816173759-58beaf3b5bd0/send.go:43 +0xbd
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: main.(*Portal).generateMessageInfo(0xc005347000, 0xc0025c3dc0)
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]:         /builds/mautrix/whatsapp/portal.go:4144 +0x28
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: main.(*Portal).HandleMatrixMessage(0xc005347000, 0xc004dcb688?, 0xc0033ccd00, {0x1774360de137, 0x0, 0x15af, 0x177b, 0x177436135a1c, 0x0, 0x0, ...})
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]:         /builds/mautrix/whatsapp/portal.go:4238 +0x1475
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: main.(*Portal).handleMatrixMessageLoopItem(0xc005347000, {0xc0033ccd00, 0xc000c401c0, {0xc13493e51e088d69, 0x157015877a, 0x1a18f40}})
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]:         /builds/mautrix/whatsapp/portal.go:344 +0x4a5
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: main.(*Portal).handleMessageLoop(0xc005347000)
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]:         /builds/mautrix/whatsapp/portal.go:401 +0x165
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]: created by main.(*WABridge).newBlankPortal in goroutine 29
Sep 01 14:24:52 pong matrix-mautrix-whatsapp[374683]:         /builds/mautrix/whatsapp/portal.go:205 +0x551
```

Anything else I can look at?

I'm running the latest docker image:
`dock.mau.dev/mautrix/whatsapp                 v0.10.0`

with ubuntu 22.04

**Comment by thorstenfx** [comment]
please someone know ?
