### ISSUE TITLE
Error on decrypting when new contact enter in contact

### ISSUE THREAD

**Issue by Valdenirmezadri** [tulir/whatsmeow#69]
was error on decrypting to 554788749284.0:7@s.whatsapp.net in 554788749284@s.whatsapp.net at 2022-03-10 15:39:29 -0300 -03

**Comment by fcerd95** [comment]
I have same issue

**Comment by Valdenirmezadri** [comment]
> I have same issue

did you manage to solve the problem?

**Comment by fcerd95** [comment]
No, i think it is whatsapp web issue :cry:

**Comment by lucianospectre** [comment]
Same issue here. Looks like a problem between WA versions. If a connect the same device i am using with meow on Whats Web, the message is not loaded there as well, instead, a "Waiting for message" error is displayed. On the device itself i can see the sender message.

Got in contact with Whatsapp Support, since this problem happens outside this repository. They replied that old What's Versions (Probably versions before multi-device was around) is having in fact a problem with versions post 2.22.3.77 ( android devices) and 2.2206.5 (Web).

**Comment by lucianospectre** [comment]
04/18/2022 - Still having this issue. Even on my personal phone, whats web is a mess

**Comment by hrizal** [comment]
Same Issue :

_[client.go 511] Event handler panicked while handling a *events.Message: runtime error: slice bounds out of range [:-1]
goroutine 21 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
go.mau.fi/whatsmeow.(*Client).dispatchEvent.func1()
        /home/go/whatsmeow-main/client.go:511 +0x7d
panic({0xae63e0, 0xc000038810})
        /usr/local/go/src/runtime/panic.go:838 +0x207
main.handler({0xa28fa0?, 0xc0003deb40})
        /home/go/whatsmeow-main/newwadev/main.go:1144 +0x22ad
go.mau.fi/whatsmeow.(*Client).dispatchEvent(0x31?, {0xa28fa0, 0xc0003deb40})
        /home/go/whatsmeow-main/client.go:515 +0x118
go.mau.fi/whatsmeow.(*Client).handleDecryptedMessage(0xc00018e000, 0xc000173d40, 0xc0002d7980)
        /home/go/whatsmeow-main/message.go:402 +0x4ee
go.mau.fi/whatsmeow.(*Client).decryptMessages(0xc00018e000, 0xc000173d40, 0xc000301800)
        /home/go/whatsmeow-main/message.go:167 +0x95a
go.mau.fi/whatsmeow.(*Client).handleEncryptedMessage(0xc00018e000, 0x0?)
        /home/go/whatsmeow-main/message.go:46 +0x1a7
go.mau.fi/whatsmeow.(*Client).handlerQueueLoop(0xc00018e000, {0xc12240, 0xc000076a40})
        /home/go/whatsmeow-main/client.go:482 +0x6b
created by go.mau.fi/whatsmeow.(*Client).Connect
        /home/go/whatsmeow-main/client.go:247 +0x45b_

**Comment by tulir** [comment]
#160 / #161
